### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by anyuese** [insitro/insitro-research#4]
Hello, I am very interested in this job. I also did some jobs about del with Machine learning. So I download the code and run.
but some files were missed. Can you privde them. Thank you very much.

Missed files list:
cnn_feats_JACS_full.pt
cnn_feats_hca_ChEMBL.pt

**Comment by bensonc-insitro** [comment]
We've added the files to the repo, and additional information in the readme to replicate our results.
